### ISSUE TITLE
memcached manque probablement dans le conteneur docker

### ISSUE THREAD

**Issue by kerphi** [arnouldpy/carto_istex#3]
root@efe7a5e0c975:/# tail /var/log/apache2/error.log
    main()
  File "Requestprocessing.py", line 227, in main
    jsondata = mc.get(sys.argv[1])
pylibmc.ConnectionError: error 3 from memcached_get(8b373710bcf876edd91f281e50ed58ab): (0x1e301a0) CONNECTION FAILURE,  host: 127.0.0.1:11211 -> libmemcached/get.cc:314
Traceback (most recent call last):
  File "Requestprocessing.py", line 256, in <module>
    main()
  File "Requestprocessing.py", line 227, in main
    jsondata = mc.get(sys.argv[1])
pylibmc.ConnectionError: error 3 from memcached_get(3389dae361af79b04c9c8e7057f60cc6): (0x29531a0) CONNECTION FAILURE,  host: 127.0.0.1:11211 -> libmemcached/get.cc:314

**Comment by kerphi** [comment]
Après un /etc/init.d/memcached start ça fonctionne mieux

**Comment by arnouldpy** [comment]
ajout du lancement automatique de memcached et apache au lancement du container via le script statup.sh
